### ISSUE TITLE
The section type "seo-audit" is not valid

### ISSUE THREAD

**Issue by DiaoRod** [kirby-tools/kirby-seo-audit#3]
When logging into the Kirby panel, where an existing audit exists I see the error `The section type "seo-audit" is not valid`. Hard refresh or visiting the page a second time then shows the audit correctly. 

A timing issue?

<img width="388" alt="Screenshot 2024-09-11 at 13 11 51" src="https://github.com/user-attachments/assets/4c9089c3-3ea1-4803-bc8d-c6642cad4a06">

Plugin: [johannschopplich/seo-audit](https://kirbyseo.com/) 1.7.4
Kirby: 4.2.0
Browsers: FF 130.0 / Chrome 128.0.6613.86
OS: Mac OS

**Comment by johannschopplich** [comment]
Hi there,
Does this happen everytime logging into the Kirby Panel? Unfortunately, I can't reproduce this issue.
Can you please provide a minimum reproducible example based on Kirby's official plainkit, starterkit or your own project?

Thanks in advance!
