### ISSUE TITLE
Dutch translation prevents report generation

### ISSUE THREAD

**Issue by MRFD** [kirby-tools/kirby-seo-audit#4]
Hi,

There seems to be something wrong with the Dutch translation. When generating the report, the modal appears with the message 'Could not generate report. Please check console logs.'. The browser console shows the message `[sprintf] huh?`. This happens both when testing in a local test environment and in your [playground](https://kirbyseo.com/playground). If the Panel user's language is changed to English or German, this problem does not occur. 

It appears to have something to do with Jed, lines [544](https://github.com/kirby-tools/kirby-seo-audit/blob/b2af170a1052da641a138b1db8014e2126c79f77/src/assets/jed/index.js#L554), [558](https://github.com/kirby-tools/kirby-seo-audit/blob/b2af170a1052da641a138b1db8014e2126c79f77/src/assets/jed/index.js#L558) or [569](https://github.com/kirby-tools/kirby-seo-audit/blob/b2af170a1052da641a138b1db8014e2126c79f77/src/assets/jed/index.js#L569).

Kirby: 4.3.1
PHP: 8.2.15
Browser: Firefox 130.0.1

**Comment by johannschopplich** [comment]
Thanks for the detailed issue report! I have fixed the translation file in https://github.com/kirby-tools/kirby-seo-audit/commit/69ffc5cf008de2790696696267388c999e71dc3d.

New release will be published later today.

**Comment by johannschopplich** [comment]
[New version ready](https://github.com/kirby-tools/kirby-seo-audit/releases/tag/v1.8.5) for you!
