### ISSUE TITLE
Error message after updating to version 2.0.0 "y.config is undefined"

### ISSUE THREAD

**Issue by gbdesign2023** [kirby-tools/kirby-seo-audit#6]
After updating to version 2.0.0, the following message appears when I open the SEO report tab, which I cannot assign. 
What do I need to be aware of when updating to version 2.0.0? 
(I'm using Kirby 4.5.0)

![CleanShot 20241220_132941@2x](https://github.com/user-attachments/assets/8fe4f9a5-d4ec-4180-8db6-4d37dd4fba3a)

In addition, a link to the documentation points to an error page:

> **Getting Started**
> To get started, please refer to the [documentation](https://kirbyseo.com/docs/getting-started) for guidance on installation, configuration, and usage.

![CleanShot 20241220_132957@2x](https://github.com/user-attachments/assets/22605ca5-f196-4ab8-b41f-a49dd12afb60)

**Comment by johannschopplich** [comment]
Hi there!

Thanks for the issue report. Unfortunately, I can't reproduce your error. Neither in the [SEO Audit playground](https://kirbyseo.com/playground), nor when testing a fresh [Kirby starterkit with the SEO Audit plugin](https://github.com/kirby-tools/kirby-seo-audit-starterkit).

Can you please provide more context on the installation method as well as a minimal reproducible example for me?

**Comment by johannschopplich** [comment]
Quick follow-up question: Have you made sure to replace the entire plugin folder, not only the `index.js` files, etc.?

**Comment by johannschopplich** [comment]
Thanks for the update! Good to know it's working. Yeah, probably a caching thing. I'll keep that in mind and probably add a note in the docs.
